spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testDemo?characterEncoding=UTF-8&useSSL=true
    username: root
    password: Zt990210
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181